import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = file => fs.readFileSync(new URL('../' + file, import.meta.url), 'utf8');
const index = read('index.js');
const ui = read('notice-ui.js');
const css = read('notice-ui.css');
assert.match(index, /import \{ createNoticeUI \} from '\.\/notice-ui\.js'/);
assert.doesNotMatch(index, /globalThis\.toastr|const toaster =|bottomErrorTimer/);
assert.match(read('style.css'), /^@import url\('\.\/notice-ui\.css'\);/);
assert.match(ui, /Symbol\.for\('sillytavern\.translationNoticeDock\.v1'\)/);
assert.match(ui, /QUICK_REPLY_SELECTOR = '#qr--bar'/);
assert.match(ui, /quickReply \|\| textarea \|\| form/);
assert.match(ui, /new ResizeObserver\(schedule\)/);
assert.match(ui, /new MutationObserver/);
assert.match(ui, /visualViewport\?\.addEventListener\('resize'/);
assert.match(ui, /observer\?\.disconnect\(\); resizeObserver\?\.disconnect\(\)/);
assert.match(ui, /success: 3000, info: 4000, warning: 6000, error: 10000/);
assert.match(ui, /close\.addEventListener\('click', \(\) => handle\.close\(\)\)/);
assert.match(ui, /await onCancel\(\); handle\.close\(\)/);
assert.match(ui, /text\.textContent = String\(message/);
assert.doesNotMatch(ui, /innerHTML|fetch\(|requestSegments|extension_settings|\.abort\(/);
assert.match(index, /type: 'return',[\s\S]*?timeout: 0,[\s\S]*?원래 위치로 돌아가기/);
assert.match(index, /restorePreviousOutputReturnPosition\(position\)/);
assert.match(css, /pointer: coarse/);
console.log('PASS: all notice routes unified, safe text, shared independent dock, quick-reply/composer anchor, resize/keyboard observers, finite timeouts, close/cancel separation, and unchanged return action wiring.');
